// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrjbTY4hrgwpYbv5qyjeE1rilDV4M43uI',
    appId: '1:1007459015910:web:2acffb684652670c09ef27',
    messagingSenderId: '1007459015910',
    projectId: 'auth-f25d9',
    authDomain: 'auth-f25d9.firebaseapp.com',
    storageBucket: 'auth-f25d9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJNJM9f897zDh121jbYFMJAfsI1JrgI2c',
    appId: '1:1007459015910:android:9bab901ede0b178c09ef27',
    messagingSenderId: '1007459015910',
    projectId: 'auth-f25d9',
    storageBucket: 'auth-f25d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByDuhj58R_APeb6t9eofKzH0vw5peb44s',
    appId: '1:1007459015910:ios:f668b674b4d9286509ef27',
    messagingSenderId: '1007459015910',
    projectId: 'auth-f25d9',
    storageBucket: 'auth-f25d9.appspot.com',
    iosClientId: '1007459015910-q5vni58oukbg6m022lam72025f8fqr9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByDuhj58R_APeb6t9eofKzH0vw5peb44s',
    appId: '1:1007459015910:ios:f668b674b4d9286509ef27',
    messagingSenderId: '1007459015910',
    projectId: 'auth-f25d9',
    storageBucket: 'auth-f25d9.appspot.com',
    iosClientId: '1007459015910-q5vni58oukbg6m022lam72025f8fqr9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.mealApp',
  );
}
